require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DevicesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Device. As you add validations to Device, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Test Device', device_type_id: DeviceType.find_or_create_by(name: 'Testing Device').id, family_id: 1, managed: true }
  }

  let(:invalid_attributes) {
    { name: nil, device_type_id: -1, managed: true }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DevicesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  context 'with an authenticated user' do
    before(:each) do
      @user = FactoryGirl.create(:user)
      sign_in(@user)
    end

    describe "GET index" do
      it "assigns all devices as @devices" do
        device = FactoryGirl.create(:device, family_id: @user.member.family.id)
        get :index, {family_id: @user.member.family.id}, valid_session
        expect(assigns(:devices)).to eq([device])
      end
    end

    describe "GET show" do
      it "assigns the requested device as @device" do
        device = FactoryGirl.create(:device, family_id: @user.member.family.id)
        get :show, {family_id: @user.member.family.id, :id => device.to_param}, valid_session
        expect(assigns(:device)).to eq(device)
      end
    end

    describe "GET new" do
      it "assigns a new device as @device" do
        get :new, {family_id: @user.member.family.id}, valid_session
        expect(assigns(:device)).to be_a_new(Device)
      end
    end

    describe "GET edit" do
      it "assigns the requested device as @device" do
        device = FactoryGirl.create(:device, family_id: @user.member.family.id)
        get :edit, {family_id: @user.member.family.id, :id => device.to_param}, valid_session
        expect(assigns(:device)).to eq(device)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Device" do
          expect {
            post :create, {family_id: @user.member.family.id, :device => valid_attributes}, valid_session
          }.to change(Device, :count).by(1)
        end

        it "assigns a newly created device as @device" do
          post :create, {family_id: @user.member.family.id, :device => valid_attributes}, valid_session
          expect(assigns(:device)).to be_a(Device)
          expect(assigns(:device)).to be_persisted
        end

        it "redirects to the created device" do
          post :create, {family_id: @user.member.family.id, :device => valid_attributes}, valid_session
          expect(response).to redirect_to([@user.member.family, Device.last])
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved device as @device" do
          post :create, {family_id: @user.member.family.id, :device => invalid_attributes}, valid_session
          expect(assigns(:device)).to be_a_new(Device)
        end

        it "re-renders the 'new' template" do
          post :create, {family_id: @user.member.family.id, :device => invalid_attributes}, valid_session
          expect(response).to render_template("new")
        end
      end
    end


    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          { name: 'Updated Device', device_type_id: DeviceType.find_or_create_by(name: 'Testing Device').id, family_id: @user.member.family.id, managed: true }        }

        it "updates the requested device" do
          device = FactoryGirl.create(:device, family_id: @user.member.family.id)
          put :update, {family_id: @user.member.family.id,:id => device.to_param, :device => new_attributes}, valid_session
          device.reload
          expect(device.name).to eq('Updated Device')
        end

        it "assigns the requested device as @device" do
          device = FactoryGirl.create(:device, family_id: @user.member.family.id)
          put :update, {family_id: @user.member.family.id, :id => device.to_param, :device => valid_attributes}, valid_session
          expect(assigns(:device)).to eq(device)
        end

        it "redirects to the device" do
          device = FactoryGirl.create(:device, family_id: @user.member.family.id)
          put :update, {family_id: @user.member.family.id, :id => device.to_param, :device => valid_attributes}, valid_session
          expect(response).to redirect_to([@user.member.family, Device.last])
        end
      end

      describe "with invalid params" do
        it "assigns the device as @device" do
          device = FactoryGirl.create(:device, family_id: @user.member.family.id)
          put :update, {family_id: @user.member.family.id, :id => device.to_param, :device => invalid_attributes}, valid_session
          expect(assigns(:device)).to eq(device)
        end

        pending "re-renders the 'edit' template" do
          device = FactoryGirl.create(:device, family_id: @user.member.family.id)
          put :update, {family_id: @user.member.family.id, :id => device.to_param, :device => invalid_attributes}, valid_session
          expect(response).to render_template("edit")  #this is wrong
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested device" do
        device = FactoryGirl.create(:device, family_id: @user.member.family.id)
        expect {
          delete :destroy, {family_id: @user.member.family.id, :id => device.to_param}, valid_session
        }.to change(Device, :count).by(-1)
      end

      it "redirects to the devices list" do
        device = FactoryGirl.create(:device, family_id: @user.member.family.id)
        delete :destroy, {family_id: @user.member.family.id, :id => device.to_param}, valid_session
        expect(response).to redirect_to(family_devices_url(@user.member.family))
      end
    end

  end















end