require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TodoSchedulesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TodoSchedule. As you add validations to TodoSchedule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TodoSchedulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all todo_schedules as @todo_schedules" do
      todo_schedule = TodoSchedule.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:todo_schedules)).to eq([todo_schedule])
    end
  end

  describe "GET show" do
    it "assigns the requested todo_schedule as @todo_schedule" do
      todo_schedule = TodoSchedule.create! valid_attributes
      get :show, {:id => todo_schedule.to_param}, valid_session
      expect(assigns(:todo_schedule)).to eq(todo_schedule)
    end
  end

  describe "GET new" do
    it "assigns a new todo_schedule as @todo_schedule" do
      get :new, {}, valid_session
      expect(assigns(:todo_schedule)).to be_a_new(TodoSchedule)
    end
  end

  describe "GET edit" do
    it "assigns the requested todo_schedule as @todo_schedule" do
      todo_schedule = TodoSchedule.create! valid_attributes
      get :edit, {:id => todo_schedule.to_param}, valid_session
      expect(assigns(:todo_schedule)).to eq(todo_schedule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TodoSchedule" do
        expect {
          post :create, {:todo_schedule => valid_attributes}, valid_session
        }.to change(TodoSchedule, :count).by(1)
      end

      it "assigns a newly created todo_schedule as @todo_schedule" do
        post :create, {:todo_schedule => valid_attributes}, valid_session
        expect(assigns(:todo_schedule)).to be_a(TodoSchedule)
        expect(assigns(:todo_schedule)).to be_persisted
      end

      it "redirects to the created todo_schedule" do
        post :create, {:todo_schedule => valid_attributes}, valid_session
        expect(response).to redirect_to(TodoSchedule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved todo_schedule as @todo_schedule" do
        post :create, {:todo_schedule => invalid_attributes}, valid_session
        expect(assigns(:todo_schedule)).to be_a_new(TodoSchedule)
      end

      it "re-renders the 'new' template" do
        post :create, {:todo_schedule => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested todo_schedule" do
        todo_schedule = TodoSchedule.create! valid_attributes
        put :update, {:id => todo_schedule.to_param, :todo_schedule => new_attributes}, valid_session
        todo_schedule.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested todo_schedule as @todo_schedule" do
        todo_schedule = TodoSchedule.create! valid_attributes
        put :update, {:id => todo_schedule.to_param, :todo_schedule => valid_attributes}, valid_session
        expect(assigns(:todo_schedule)).to eq(todo_schedule)
      end

      it "redirects to the todo_schedule" do
        todo_schedule = TodoSchedule.create! valid_attributes
        put :update, {:id => todo_schedule.to_param, :todo_schedule => valid_attributes}, valid_session
        expect(response).to redirect_to(todo_schedule)
      end
    end

    describe "with invalid params" do
      it "assigns the todo_schedule as @todo_schedule" do
        todo_schedule = TodoSchedule.create! valid_attributes
        put :update, {:id => todo_schedule.to_param, :todo_schedule => invalid_attributes}, valid_session
        expect(assigns(:todo_schedule)).to eq(todo_schedule)
      end

      it "re-renders the 'edit' template" do
        todo_schedule = TodoSchedule.create! valid_attributes
        put :update, {:id => todo_schedule.to_param, :todo_schedule => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested todo_schedule" do
      todo_schedule = TodoSchedule.create! valid_attributes
      expect {
        delete :destroy, {:id => todo_schedule.to_param}, valid_session
      }.to change(TodoSchedule, :count).by(-1)
    end

    it "redirects to the todo_schedules list" do
      todo_schedule = TodoSchedule.create! valid_attributes
      delete :destroy, {:id => todo_schedule.to_param}, valid_session
      expect(response).to redirect_to(todo_schedules_url)
    end
  end

end
